{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1QZJG_sMWzeIHz_QWFWj1B9TDOBMz55Lv","timestamp":1718103842312}]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["# *Exceções*\n","\n","Exceções são situações inesperadas em nosso código ou apenas algo que não tratamos diretamente no programa.\n","\n","A estrutura ***try/except*** é usada para tratar erros em Python. Ela permite que você execute um bloco de código e, em seguida, capture e trate qualquer exceção que possa ser lançada.\n","\n","Como exemplo de exceções temos *ValueError*, *IndexError* e *ZeroDivisionError*, mostrados a seguir.\n","Essas exceções são parte da biblioteca padrão do Python. Podemos também criar as nossas próprias exceções."],"metadata":{"id":"wl0FufGbS3uA"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"Gtq4d6moB_yc","colab":{"base_uri":"https://localhost:8080/","height":110},"executionInfo":{"status":"error","timestamp":1718103743397,"user_tz":180,"elapsed":6,"user":{"displayName":"Thaís Schmidt","userId":"13201277855324628709"}},"outputId":"73132610-a405-4323-edd0-25cbea98675f"},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"unterminated string literal (detected at line 2) (<ipython-input-1-67da1004d3c5>, line 2)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-67da1004d3c5>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    print('Hello)\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m unterminated string literal (detected at line 2)\n"]}],"source":["# Leia a mensagem de erro (SyntaxError)\n","print('Hello)"]},{"cell_type":"code","source":["# Leia a mensagem de erro (TypeError)\n","8 + 's'"],"metadata":{"id":"J26tTRe3lkq-","executionInfo":{"status":"error","timestamp":1718056149258,"user_tz":180,"elapsed":339,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"colab":{"base_uri":"https://localhost:8080/","height":165},"outputId":"931e7718-ca06-49f6-eb2a-fefe1b72e504"},"execution_count":null,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"unsupported operand type(s) for +: 'int' and 'str'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-649df8de3af4>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Erro (leia a mensagem de erro)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;36m8\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m's'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}]},{"cell_type":"code","source":["# Criando uma função de divisão\n","\n","def numDiv (num1, num2):\n","  resultado = num1 / num2\n","  print(resultado)"],"metadata":{"id":"xF7ayP6Vl9Wr"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# Execução sem erro\n","numDiv(4,2)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"KVDZfqzVmDMn","executionInfo":{"status":"ok","timestamp":1718056164935,"user_tz":180,"elapsed":320,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"c8ac0e3f-9fb2-43fb-d928-206f97b1c2c4"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["2.0\n"]}]},{"cell_type":"code","source":["# Execução gerando erro (ZeroDivisionError)\n","numDiv(4,0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":274},"id":"xixb-OjomE3d","executionInfo":{"status":"error","timestamp":1718056167728,"user_tz":180,"elapsed":307,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"6b767baf-fd2c-43c6-e747-c3e391be38e9"},"execution_count":null,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-127202d6cf68>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Execução gerando erro (leia a mensagem de erro)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mnumDiv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-3-3decf975bb94>\u001b[0m in \u001b[0;36mnumDiv\u001b[0;34m(num1, num2)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Criando uma função de divisão\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mnumDiv\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mnum1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m   \u001b[0mresultado\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnum1\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mnum2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresultado\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","source":["### A estrutura ***try except finally*** tem a sintaxe que veremos a seguir.\n","Observe que, após executar o código após ***try***, em vez de retornar um erro, será executado o código de tratamento que escreveremos no bloco após ***except***."],"metadata":{"id":"xu53nlkmmoq_"}},{"cell_type":"code","source":["# Utilizando try e except\n","try:\n","  8 + 's'\n","except TypeError:\n","  print(\"Operação não permitida\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"g5f1tnqum0h3","executionInfo":{"status":"ok","timestamp":1718049056257,"user_tz":180,"elapsed":1103,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"717e343e-9140-458f-fd09-71adf02b2793"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Operação não permitida\n"]}]},{"cell_type":"markdown","source":["Os comandos no bloco ***finally*** são sempre executados!"],"metadata":{"id":"w4j5AvO0pObK"}},{"cell_type":"code","source":["def askint():\n","  try:\n","    val = int((input(\"Digite um número: \")))\n","  except ValueError:\n","    print (\"Você não digitou um número!\")\n","  finally:\n","    print (\"Obrigado!\")"],"metadata":{"id":"hRKrFHRvm1Dk"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# Execute uma chamada a esta função digitando um número e não haverá erro a ser tratado.\n","# Digite a seguir uma letra e veja que, em vez de uma mensagem de erro, teremos a nossa mensagem como saída.\n","askint()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"LvHVRErwoIsR","executionInfo":{"status":"ok","timestamp":1718065898496,"user_tz":180,"elapsed":3028,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"a3a7f7a5-35dc-4e8b-b46e-7ba800b03398"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite um número: 6\n","Obrigado!\n"]}]},{"cell_type":"code","source":["# Podemos incrementar o nosso programa perguntando novamente em caso de erro.\n","\n","def askint():\n","  try:\n","    val = int(input(\"Digite um número: \"))\n","  except ValueError:\n","    print (\"Você não digitou um número!\")\n","    val = int(input(\"Tente novamente. Digite um número: \"))\n","  finally:\n","    print (\"Obrigado!\")\n","\n","  print (val)"],"metadata":{"id":"uUHsuRuLowZE"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["askint()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"S37jCM_ZpDCp","executionInfo":{"status":"ok","timestamp":1718048057037,"user_tz":180,"elapsed":1774,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"a996e881-e464-490d-858a-1a5d2e97bae7"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite um número: 5\n","Obrigado!\n","5\n"]}]},{"cell_type":"markdown","source":["Você deve ter percebido que não resolveu o problema ainda pois não tratamos o caso de errar duas vezes.\n","Podemos usar então a estrutura ***while***, enquanto não digitar corretamente o bloco continuará perguntando."],"metadata":{"id":"CBnB06HGpPpl"}},{"cell_type":"code","source":["def askint():\n","  while True:\n","    try:\n","      val = int(input(\"Digite um número: \"))\n","    except ValueError:\n","      print (\"Você não digitou um número!\")\n","      continue\n","    else:\n","      print (\"Obrigado por digitar um número!\")\n","      break\n","    finally:\n","      print(\"Fim da bloco try!\")\n","\n","  print (val)"],"metadata":{"id":"TbdokyaKpO66"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["askint()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"lcMJHvytp9Z_","outputId":"7f9c722a-e015-4210-b515-7f3ef1e12698","executionInfo":{"status":"ok","timestamp":1718063868873,"user_tz":180,"elapsed":33306,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}}},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite um número: f\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: l\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: i\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: io\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: po\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: ki\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: k\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: p\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: ç\n","Você não digitou um número!\n","Fim da bloco try!\n","Digite um número: 4\n","Obrigado por digitar um número!\n","Fim da bloco try!\n","4\n"]}]},{"cell_type":"markdown","source":["### Podemos tratar as exceções diferentes de forma personalizada, com várias declarações except, como no exemplo a seguir."],"metadata":{"id":"rUbV4jTjJP_C"}},{"cell_type":"code","source":["nomes = [\"Alex\", \"Marcos\", \"João\", \"Uwe\"]\n","\n","for tentativa in range(5):\n","  try:\n","    i = int(input(\"Digite o índice do nome que você que imprimir:\"))\n","    print(nomes[i])\n","  except ValueError:\n","    print(\"Digite um número!\") # \"Tratando\" o erro ValueError\n","  except IndexError:\n","     print(\"Valor fora da faixa válida, digite um número de -4 a 3\") # \"Tratando\" o erro IndexError\n","\n","# Forneça um número fora da faixa e uma letra para testar o tratamento de erro"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"XhE0eCSlJPbc","executionInfo":{"status":"ok","timestamp":1718066329515,"user_tz":180,"elapsed":20611,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"cccf55b4-0fc5-4e51-c538-6eb6b9ce7100"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite o índice do nome que você que imprimir:2\n","João\n","Digite o índice do nome que você que imprimir:d\n","Digite um número!\n","Digite o índice do nome que você que imprimir:8\n","Valor fora da faixa válida, digite um número de -4 a 3\n","Digite o índice do nome que você que imprimir:0\n","Alex\n","Digite o índice do nome que você que imprimir:5\n","Valor fora da faixa válida, digite um número de -4 a 3\n"]}]},{"cell_type":"markdown","source":["### A parte do código que terá a sua exceção tratada é somente o que estiver entre *try e except* e tratará somente as exceções *ValueError* e *IndexError* que foram passadas.\n","Ou seja, se ocorrer uma exceção diferente, o programa abortará e dará uma mensagem de erro.\n","\n","## Para tratar qualquer exceção de uma forma única, podemos deixar vazio após *except:*\n","\n","Veja o exemplo abaixo:"],"metadata":{"id":"mITkXV_3mrLt"}},{"cell_type":"code","source":["nomes = [\"Alex\", \"Marcos\", \"João\", \"Uwe\"]\n","\n","for tentativa in range(3):\n","  try:\n","    i = int(input(\"Digite o índice do nome que você que imprimir:\"))\n","    print(nomes[i])\n","  except:\n","    print(\"O valor digitado não é valido\") # \"Tratando um erro genericamente\"\n","# Teste os dois casos de erros anteriores e veja que serão tratados aqui de uma forma única."],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"i_7YEwj8oL2L","executionInfo":{"status":"ok","timestamp":1718066501720,"user_tz":180,"elapsed":7438,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"b6a24ac1-ee24-4924-ea0f-ee5f53a5611b"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite o índice do nome que você que imprimir:5\n","O valor digitado não é valido\n","Digite o índice do nome que você que imprimir:2\n","João\n","Digite o índice do nome que você que imprimir:3\n","Uwe\n"]}]},{"cell_type":"markdown","source":["## Para tratar qualquer exceção e mostrar o erro ocorrido, podemos usar o tipo raiz ***Exception*** após a cláusula *except*\n","\n","Veja o exemplo abaixo, onde renomeamos ***Exception*** como ***erro***:"],"metadata":{"id":"n6N0NzIcv_-q"}},{"cell_type":"code","source":["nomes = [\"Alex\", \"Marcos\", \"João\", \"Uwe\"]\n","\n","for tentativa in range(3):\n","  try:\n","    i = int(input(\"Digite o índice do nome que você que imprimir:\"))\n","    print(nomes[i])\n","  except Exception as erro:\n","    print(f\"Ocorreu o erro: {erro}\") # \"Tratando um erro genericamente\" e mostrando a mensagem deste erro\n","# Teste os dois casos de erros anteriores e veja que serão tratados aqui de uma forma única."],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_sfjQY4Svm0X","executionInfo":{"status":"ok","timestamp":1718066944564,"user_tz":180,"elapsed":19131,"user":{"displayName":"Alex de Oliveira Penteado","userId":"14297955292311485689"}},"outputId":"16662534-cb8f-4b01-b340-6f964a874f82"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Digite o índice do nome que você que imprimir:8\n","Ocorreu o erro: list index out of range\n","Digite o índice do nome que você que imprimir:g\n","Ocorreu o erro: invalid literal for int() with base 10: 'g'\n","Digite o índice do nome que você que imprimir:1\n","Marcos\n"]}]},{"cell_type":"markdown","source":["Uma lista completa de exceções em Python pode ser encontrada na documentação disponível no site:\n","https://docs.python.org/3.12/library/exceptions.html"],"metadata":{"id":"Kn3daaQ7r-XR"}}]}